### ISSUE TITLE
trigger bot setting off anticheat + how to fix [Suggestion] 

### ISSUE THREAD

**Issue by gnimagix** [MatHax/Client#100]
### Describe the feature

when ever i use the trigger bot module under combat , the anticheat (vulcan) detects it and flags it for "post UseEntity Packets" and "impossible consistency"...

I think that issue could be resolved by adding customization to the module by adding random hit consistency and making sothat whenever you look at the entity the autoclicker starts to hit instead of using Use packets to hit the entity.

im not a coder, and might not know if what im saying makes sense, but to me it seems like it would work out of experience from many other Utility Clients ive used and tested.

Meteor/Mathax is by far my favourite  because of all the modules and customization you can bring to them. :p

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Rorschach3533** [comment]
trigger bot attack time is not correct btw its not attacking on fullbar it attack few miliseconds before and I cant sweep
