### ISSUE TITLE
Using Alto Clef AI instead of Baritone [Suggestion] 

### ISSUE THREAD

**Issue by IrshaadAli1** [MatHax/Client#103]
### Describe the feature

In a nutshell, it is a smarter AI version that can do things progressively. For Example:

Baritone: When you want to get iron and use ".mine iron_ore" the baritone bot will just mine iron ore with their fist if you just spawned into a new world.

Alto Clef: When you want to get iron and use a command to get iron ore, the AI will mine the wood, make a wooden pickaxe, mine stone, then make a stone pickaxe, then mine the iron ore when you spawn in.

Link to the video clip where I found out about it: https://www.youtube.com/watch?v=2V5-NC1eqWI&t=127s

Install Link:
https://github.com/gaucho-matrero/altoclef

Link to the Tutorial: https://www.youtube.com/watch?v=22r0ynu3oZE
### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by PiotrekUnityDeveloper** [comment]
lool just install it along the client
