### ISSUE TITLE
[Bug] Baritone crashes when you use t launcher.

### ISSUE THREAD

**Issue by githubguy500** [MatHax/Client#11]
### Describe the bug

When you start baritone with " #mine diamond_ore" it works for some seconds and then crashes for no reason 

### Steps to reproduce

```bash
you do "#mine diamond_ore" then wait like 4 to 3 seconds then it crashes
```

### MatHax Legacy Version

MatHax_Legacy-v1.6.4-Fabric

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Send the crash report/log.
