### ISSUE TITLE
[Suggestion] re-add a mod .jar download

### ISSUE THREAD

**Issue by MrMcyeet** [MatHax/Client#111]
### Describe the feature

This may be an unpopular opinion, but I think it would be useful for there to be a place to download releases `(and previous releases)` directly from either the site or this repo.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by a-a3458** [comment]
they have a installer which puts the jar file in the mods folder

**Comment by PiotrekUnityDeveloper** [comment]
UPVOTE!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Matejko06** [comment]
We will add manual download option under the installer download button on the new website when its done.
