### ISSUE TITLE
Crash when booting on M1 mac

### ISSUE THREAD

**Issue by FeminineFemale** [MatHax/Client#115]
### Describe the bug

https://pastebin.com/xSLbNByC crash log
 I am using a multimc fork called manymc and using https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk fork of java

### Steps to reproduce

```bash
launch mathax on m1 mac with apple "kind"
```

### MatHax Version

MatHax-v1.7.4-Fabric_1.18.2.jar

### Minecraft Version

1.18.2

### Operating System

macOS

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by FeminineFemale** [comment]
issue still exists in 1.7.5

**Comment by dudethis** [comment]
Yup happens on all arm cpus, its because of the discord rpc it tries to load which is for amd64

**Comment by dudethis** [comment]
Since your on a mac, I'm pretty sure you are able to fix this using rosetta since it imitates intel chips. (" Rosetta is a translation process that allows users to run apps that contain x86_64 instructions on Apple silicon")

**Comment by FeminineFemale** [comment]
> Since your on a mac, I'm pretty sure you are able to fix this using rosetta since it imitates intel chips. (" Rosetta is a translation process that allows users to run apps that contain x86_64 instructions on Apple silicon")

Yes but it degrades fps when using rosetta

**Comment by master7720** [comment]
> ### Describe the bug
> https://pastebin.com/xSLbNByC crash log I am using a multimc fork called manymc and using https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk fork of java
> 
> ### Steps to reproduce
> ```shell
> launch mathax on m1 mac with apple "kind"
> ```
> 
> ### MatHax Version
> MatHax-v1.7.4-Fabric_1.18.2.jar
> 
> ### Minecraft Version
> 1.18.2
> 
> ### Operating System
> macOS
> 
> ### Before submitting a bug report
> * [x]  This bug wasn't already reported.
>   (I have checked every bug report on github)
> * [x]  This is a valid bug.
>   (I am able to reproduce this on the latest dev build)

Heres a fix dont use macOS

**Comment by dudethis** [comment]
> > ### Describe the bug
> > https://pastebin.com/xSLbNByC crash log I am using a multimc fork called manymc and using https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk fork of java
> > ### Steps to reproduce
> > ```shell
> > launch mathax on m1 mac with apple "kind"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### MatHax Version
> > MatHax-v1.7.4-Fabric_1.18.2.jar
> > ### Minecraft Version
> > 1.18.2
> > ### Operating System
> > macOS
> > ### Before submitting a bug report
> > 
> > * [x]   This bug wasn't already reported.
> >   (I have checked every bug report on github)
> > * [x]   This is a valid bug.
> >   (I am able to reproduce this on the latest dev build)
> 
> Heres a fix dont use macOS
Actually its not a macOS problem, but instead the cpu architecture being arm64. Arm cpu's use way less energy than traditional intel cpu's, and their fast. Future is arm and we need to adapt to it.

**Comment by dudethis** [comment]
Ares client as well as many others have soved the issue by disabling it on start
![image](https://user-images.githubusercontent.com/83372797/168740641-72659afc-e1c5-4b24-94a4-5b830be408bb.png)
