### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HUNAttila32** [MatHax/Client#117]
### Describe the bug

Crashes MatHax without loading.

### Steps to reproduce

```bash
By launching the game. 1.18.2 fabric.
```

### MatHax Version

1.7.2

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Update MatHax, you're 2 versions behind.
