### ISSUE TITLE
[Bug] Xray

### ISSUE THREAD

**Issue by Wattville** [MatHax/Client#118]
### Describe the bug

Xray is not working.
![image](https://user-images.githubusercontent.com/85033762/160248527-8a2b17fd-1395-4289-bad0-714208d5ee31.png)

### Steps to reproduce

```bash
Turning on Xray.
```

### MatHax Version

1.17.1 - newest

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Any other mods?
