### ISSUE TITLE
[Suggestion] Add Mojang auth back

### ISSUE THREAD

**Issue by PilaCiu** [MatHax/Client#125]
### Describe the feature

Most accounts still work so it's useful

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
Next update will have it.
