### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by HUNAttila32** [MatHax/Client#126]
### Describe the feature

Binding with the .bind command. It's in every version of meteor, and you guys didn't include the feature. If you could add it, maybe i will use mathax frequently and may even use meteor too for utility.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
Added, next update will contain it.
