### ISSUE TITLE
[Suggestion] fight bot

### ISSUE THREAD

**Issue by tholvibt** [MatHax/Client#127]
### Describe the feature

can you make a fightbot that walks and kill mobs and player automatically like in wurst client
i loves mathax but it has no fight bot and also make protect bot which protect nearest entity like in wurst client
and bot's brain want to be like bartone

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Zaxxoid2** [comment]
Good idea.
