### ISSUE TITLE
[Bug] Ignore Self dont work

### ISSUE THREAD

**Issue by FurnyGo** [MatHax/Client#129]
### Describe the bug

![image](https://user-images.githubusercontent.com/68079109/162784395-135b60e3-fbfb-429b-82bc-f8ff5e73a20a.png)

### Steps to reproduce

```bash
Spam - active
Ignore self - active/deactive
```

### MatHax Version

1.7.5

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Fixed for 1.7.6+
