### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by MaximeG12** [MatHax/Client#132]
### Describe the feature

mathax client,become mathax addon meteor

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by C10udburst** [comment]
ez fix:
just download meteor and all the addons from github and you'll have all mathax features and more

**Comment by maplepy** [comment]
Thing is, MatHax does have some features Meteor don't have and no other module has
