### ISSUE TITLE
[Suggestion] add a volume slider for the music player

### ISSUE THREAD

**Issue by Ayloten** [MatHax/Client#151]
### Describe the feature

For me, I can't really turn down the music without having to turn down the rest of my computer sounds. what would be extremely helpful would to add a volume slider that is in the same sub section (music and sounds) as the other game sounds. this way it would be easy for someone to find a way to turn down the music.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
Config tab in click GUI
