### ISSUE TITLE
[Suggestion] Disable chat reports

### ISSUE THREAD

**Issue by PY3-3** [MatHax/Client#168]
### Describe the feature

just remove the chat report system.
Nobody likes it.-

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by fluorek** [comment]
https://github.com/Aizistral-Studios/No-Chat-Reports
