### ISSUE TITLE
I think its a [Bug] 

### ISSUE THREAD

**Issue by BrilliePlays** [MatHax/Client#179]
### Describe the bug

When i open the installer, it doesnt open and instead just says something along the lines of "The installer was unable to fetch metadata from the server, check your internet connection and try again"

### Steps to reproduce

```bash
Open the Installer, says  "The installer was unable to fetch metadata from the server, check your internet connection and try again" then only options is to close the error message.
```

### MatHax Version

Installer 1.0.9

### Minecraft Version

No Certian Minecraft Version

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Update Java

**Comment by BrilliePlays** [comment]
ok
