### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Savvakos7** [MatHax/Client#18]
### Describe the bug

*Message lagger completely crashes your game at any config
*Minecraft is very laggy with this specific client (lag on wifi)

### Steps to reproduce

```bash
By enabling message lagger
```

### MatHax Legacy Version

Latest

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MrMcyeet** [comment]
+1
I too have this issue
Windows 10
adoptium java 16
