### ISSUE TITLE
[Bug] . Commands

### ISSUE THREAD

**Issue by DaddyGhast** [MatHax/Client#191]
### Describe the bug

When I try to do and . command it actually sends it in chat so everyone can see it, I dont know if I am doing something wrong 

### Steps to reproduce

```bash
Not sure
```

### MatHax Version

v1.7.6

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Check if you didn't change the prefix or if you even have the client.
