### ISSUE TITLE
[Suggestion] Tunnel Highlighter

### ISSUE THREAD

**Issue by Jonathan274** [MatHax/Client#21]
### Describe the feature

Hi.

Would it be possible to have a tunnel highlighter as a render option. The way it would work is by highlighting 2x1 tunnels. It would make base hunting a lot easier, especially on smaller anarchy servers. Cause a big portion of players use tunnels as a means of transportation, and use them to get away from spawn to make their base. Plus I feel like this would be easy to implement.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by pvppoverty** [comment]
oh wow  this would actually be useful also maybe a setting to change the size of the hole u want to find, sorta like a customizable cave finder

**Comment by Matejko06** [comment]
Tunnel ESP
