### ISSUE TITLE
[Bug] when i use the no render and it crach instantly 

### ISSUE THREAD

**Issue by Itop8** [MatHax/Client#33]
### Describe the bug

Instantly crash when turn on no render not sure if it happen with other hack module

### Steps to reproduce

```bash
Open the client
Turn on no render
Crash
```

### MatHax Legacy Version

1.6.7

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Could i get a log?

**Comment by Itop8** [comment]
[latest.log](https://github.com/MatHax/Legacy/files/7766291/latest.log)

**Comment by fluorek** [comment]
if you have fabric api it may be his fault

**Comment by Itop8** [comment]
I still get crash when i turn off all the mod
