### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by imjaylolheh** [MatHax/Client#42]
### Describe the bug

my game crash when i put mathax on my mods folder when i started minecraft

### Steps to reproduce

```bash
i dont know
```

### MatHax Legacy Version

v.1.6.7 - v-1.6.9

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Could i get a log?
