### ISSUE TITLE
turn no render on and instantly crah

### ISSUE THREAD

**Issue by Itop8** [MatHax/Client#44]
### Describe the bug

same as the old one

### Steps to reproduce

```bash
open client and turn on no render 
instantly crash
```

### MatHax Legacy Version

1.6.9

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by CheatTerminator** [comment]
Similar problem, tho it crashes when I try to change no render settings, the module itself works fine.

**Comment by Itop8** [comment]
Sometime it crash when i join a server without turning on render

**Comment by Matejko06** [comment]
Could i get both logs?

**Comment by Itop8** [comment]
[latest.log](https://github.com/MatHax/Legacy/files/7793629/latest.log)

**Comment by Matejko06** [comment]
> [latest.log](https://github.com/MatHax/Legacy/files/7793629/latest.log)

Issue with tl_skin_cape_fabric-1.16.5_1.19.jar

**Comment by Itop8** [comment]
this is the crash log in the newest version no mod

**Comment by Itop8** [comment]
[latest.log](https://github.com/MatHax/Client/files/7799042/latest.log)
