### ISSUE TITLE
Crash when Spawn Proofer runs out of torches [Bug] 

### ISSUE THREAD

**Issue by p3iurhgmc98h** [MatHax/Client#45]
### Describe the bug

The spawn-proofer module causes a crash if it's on and the player runs out of torches (or other usable items).
If the player attempts to start the module without any usable items in the hotbar, an error message is displayed and the module disables itself (this works as intended).
However, if the module places the last available item and has no more available, the game immediately crashes to desktop.

### Steps to reproduce

```bash
1. Place torches in your hotbar.
2. Enable Spawn Proofer.
3. Wait until you run out of torches.
4. Crash.
```

### MatHax Legacy Version

1.6.9

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Does this still happen in 1.7.0?

**Comment by p3iurhgmc98h** [comment]
Sorry, didn't realize there was a new release. Doesn't seem to be happening in 1.7.0.
Thanks, and sorry for the trouble.
