### ISSUE TITLE
[Bug] Auto eat

### ISSUE THREAD

**Issue by Robounknown** [MatHax/Client#46]
### Describe the bug

Auto eat function does not pause baritone during .b sel ca
constantly tries to eat between breaking blocks causing it to get stuck and canceling any killaura combat

### Steps to reproduce

```bash
pick a large area with .b sel 1 and 2 and start .b sel ca
once it tries to eat you will see
```

### MatHax Version

latest

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by pog5** [comment]
Have you enabled Pause Baritone in the Module's settings?
