### ISSUE TITLE
[Bug] playing music sometimes crashes the client

### ISSUE THREAD

**Issue by SanderLippa** [MatHax/Client#50]
### Describe the bug

Sometimes when i attempt to load a song from a playlist the client crashes

### Steps to reproduce

```bash
play a song
wait until it ends
select another song
(after a few tries it will work)
```

### MatHax Version

1.7.0

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Could i get a log?
