### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by FinishedCoot73** [MatHax/Client#54]
### Describe the feature

bro add fly back, why did u remove it

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
??????????

**Comment by FinishedCoot73** [comment]
why did u remove the "fly" module



śr., 5 sty 2022 o 12:44 Matejko06 ***@***.***> napisał(a):

**Comment by QuartzWarrior** [comment]
Its called `flight`
