### ISSUE TITLE
[Bug] crash when turning on piston aura

### ISSUE THREAD

**Issue by Itop8** [MatHax/Client#56]
### Describe the bug

like the name

### Steps to reproduce

```bash
start the client
turn on piston aura
crash
```

### MatHax Version

1.7.0

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Itop8** [comment]
[latest.log](https://github.com/MatHax/Client/files/7822585/latest.log)

**Comment by Ladybells** [comment]
Try removing soduim. Soduim caused alot of issues on my client including chunk loading breaking outside 1M+ in x or y
