### ISSUE TITLE
[Suggestion] Credits

### ISSUE THREAD

**Issue by cally72jhb** [MatHax/Client#57]
### Describe the feature

At least, credit the work of others if you steal their code.
Credit them in the module description or on your website please.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by BruhBruhStupidCoder** [comment]
Agreed with this one

**Comment by Matejko06** [comment]
I didnt comit for so long because of this. Every module is getting all info into its desc. :)

**Comment by cally72jhb** [comment]
thanks

**Comment by FinishedCoot73** [comment]
we credit meteor on the website lol

**Comment by Matejko06** [comment]
@FinishedCoot73 addons exist
