### ISSUE TITLE
[Suggestion] Add Force OP

### ISSUE THREAD

**Issue by jekkelock** [MatHax/Client#59]
### Describe the feature

In the Wurst Client there is an option called ForceOP. Its description states that: Force OP (a.k.a. AuthMe Cracker) is a mod that cracks AuthMe passwords. It can be used on AuthMe servers to force OP yourself by cracking the AuthMe password of an admin or to get access to other people’s plots and items by cracking their AuthMe password.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Cypphi** [comment]
Why, just why, bruteforcing takes years

**Comment by Eccentrici** [comment]
When was the last time you successfully used ForceOP on another client?

**Comment by forota123** [comment]
:troll:

**Comment by Theboiboi8** [comment]
meteor has such a feature, utilizing the meteor library
you just have to write some cryptic text in a book and throw it at someone with op

**Comment by bluaxd** [comment]
forceop is outdated nowadays xd

**Comment by Theboiboi8** [comment]
I mean yea, but still, just add it for the people that want it
