### ISSUE TITLE
[Suggestion] elytra bot

### ISSUE THREAD

**Issue by Itop8** [MatHax/Client#66]
### Describe the feature

Baritone elytra

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by pog5** [comment]
This is a baritone related feature, please suggest it on their GitHub at https://github.com/cabaletta/baritone
