### ISSUE TITLE
[Bug] crash java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$13" is null

### ISSUE THREAD

**Issue by lightningmc09** [MatHax/Client#67]
### Describe the bug

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$13" is null
when i load game
crash report:
[crash-2022-01-18_19.39.14-client.txt](https://github.com/MatHax/Client/files/7893475/crash-2022-01-18_19.39.14-client.txt)

### Steps to reproduce

```bash
load game
```

### MatHax Version

1.7.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [x] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by pog5** [comment]
Try using the newest java from http://java.com/download

**Comment by white-devil42** [comment]
Try removing all other mods (if you use any)
