### ISSUE TITLE
[Suggestion] Add option to hide modules

### ISSUE THREAD

**Issue by liadinon** [MatHax/Client#69]
### Describe the feature

There are a lot of modules and I don't need all of them, most of them just make it harder to find the modules I want.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by white-devil42** [comment]
use the search
