### ISSUE TITLE
[Suggestion] Add compatibility for Meteor Addons

### ISSUE THREAD

**Issue by Theboiboi8** [MatHax/Client#75]
### Describe the feature

Add some sort of compatibility layer on top of the client to parse addons made for Meteor to work with MatHax so players can use addons not included in MatHax by default

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **repository**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
I would love to see how lol

**Comment by maplepy** [comment]
Maybe fake the mod as `meteor-client`?

**Comment by Theboiboi8** [comment]
Don't think it'll work, MatHax has different files that Meteor, addons
wouldn't know where to look for what

**Comment by maplepy** [comment]
Yeah probably :/
