### ISSUE TITLE
[Bug] Client crashes when you open settings of plasmo voice

### ISSUE THREAD

**Issue by Blackflexxy** [MatHax/Client#79]
### Describe the bug

After you open settings of plasmo voice client crashes

### Steps to reproduce

```bash
Install MatHax
Install Plasmo Voice
Press v or your custom keybind to open Plasmo voice settings
```

### MatHax Version

1.7.0/1.7.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Theboiboi8** [comment]
I personally open the plasmo voice settings just fine with MatHax, maybe it's some sort of keybind issue on your end

**Comment by Theboiboi8** [comment]
this appears to only happen on servers with plasmo voice installed and on singleplayer
