### ISSUE TITLE
[Suggestion] List of features to add

### ISSUE THREAD

**Issue by elderendlord** [MatHax/Client#8]
### Describe the feature

Easy

1. Removes player model and turns them into fat rats. << Vary funny.
2. Like more packet bypasses to crystal aura and packet fly ect.
3. more swarm commands
4. More Ncp options for building and mining utility's.
^^ Such as placing blocks in mid air.

Medium

More Loggers. 
Example: coord logger.
base esp. ect.

More Smart Ai for kill aura and crystal aura settings.
Lots more crystal aura settings.

Hard.

4. All files you need to launch mathax built in. Like: Fabric api, Mods menu, and via fabric.
5. Custom Auto Pilot for elytra. Also try's to dodge objects, and auto elytra for when your main runs out. and automaticly activates elytra.
^^ or Musk Mode
6. pvp bot. Kinda like wursts pvp bot but smarter.
7. Kill Hack: Drinks Strength potions and critical swords someone till they get out of there hole then crystals them when the move out of the hole.
8: Multiplayer menu overhull. Adds the background of mathax in both modes.
9: Built in Google engine.

Fun things to add:

1:Fake creative.
2: Tease: Strafes side to side vary quickly.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Matejko06** [comment]
All needed dependencies are already built in. MatHax doesn't need Fabric API.
Fake creative is already a command.
