### ISSUE TITLE
[Bug] Cannot close brewing stand gui

### ISSUE THREAD

**Issue by white-devil42** [MatHax/Client#82]
### Describe the bug

Cannot close brewing stand gui

### Steps to reproduce

```bash
look at a brewing stand 
right click
```

### MatHax Version

1.7.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Fixed, update soon.
