### ISSUE TITLE
Cannot Exit Brewing Stand

### ISSUE THREAD

**Issue by IrshaadAli1** [MatHax/Client#84]
### Describe the bug

I Used MatHax Client and had made a brewing stand with some hacks still enabled, but when I opened the brewing stand, I couldn't exit out of it, I tried "ESC", "E" but I couldn't exit out of it, I couldn't move anything except for my mouse and me dragging the items around in my inventory. I couldn't even toggle the hack menu like Nuker to break the brewing stand
![image](https://user-images.githubusercontent.com/98787249/151895199-42abccc5-c395-4880-874e-6ad7d22577dd.png)
I keep trying but I can't seem to exit it, the image is the hacks I have on

### Steps to reproduce

```bash
I am not 100% sure but I tried it twice with the hacks I had on and this is what I had:

Auto Reconnect
Criticals: [ Packet ]
No Render
No Fall
ESP
```

### MatHax Version

1.7.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by master7720** [comment]
did you try pressing "ect"?

**Comment by master7720** [comment]
or just restart your game?

**Comment by Matejko06** [comment]
Fixed, update soon.
