### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Criss57** [MatHax/Client#86]
### Describe the bug

Proxy selection not working properly.
![image_2022-02-03_115201](https://user-images.githubusercontent.com/90045167/152319538-b3e372bc-1875-442f-8f1f-760d3cff352f.png)
https://streamable.com/67y6r1

### Steps to reproduce

```bash
It happened randomly and now I cant get rid of it
```

### MatHax Version

1.7.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Fixed, update soon.
