### ISSUE TITLE
Cannot Escape Server Finder

### ISSUE THREAD

**Issue by IrshaadAli1** [MatHax/Client#88]
### Describe the bug

Server Finder cannot be exited out with the ESC 

### Steps to reproduce

```bash
Open Server Finder
```

### MatHax Version

1.7.1

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Fixed, update soon.
