### ISSUE TITLE
[Suggestion] Sound Cloud support for Music Player

### ISSUE THREAD

**Issue by chaseunc0** [MatHax/Client#9]
### Describe the feature

2 feature suggestions
1. Allow for soundcloud Playlists in the music menu
2. Altoclef integration would be really cool

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by fluorek** [comment]
Or maybe spotify
