### ISSUE TITLE
[Bug] Can't install

### ISSUE THREAD

**Issue by ItzGabi2k** [MatHax/Client#97]
### Describe the bug

Hi! I can't install MatHax version v1.0.7.
It says > The installer was unable to fetch metadata from the server, please check your internet connection and try again later.

### Steps to reproduce

```bash
Also i have java installed. And my internet connection is ok
```

### MatHax Version

1.0.7

### Minecraft Version

1.18.1

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Try updating Java
